// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GetHonestRcpp
NumericVector GetHonestRcpp(List x, NumericVector y, NumericMatrix z, NumericMatrix w);
RcppExport SEXP _ifedtree_GetHonestRcpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(GetHonestRcpp(x, y, z, w));
    return rcpp_result_gen;
END_RCPP
}
// PredHonestRcpp
NumericVector PredHonestRcpp(List x, NumericVector y, NumericMatrix z, NumericMatrix w);
RcppExport SEXP _ifedtree_PredHonestRcpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(PredHonestRcpp(x, y, z, w));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ifedtree_GetHonestRcpp", (DL_FUNC) &_ifedtree_GetHonestRcpp, 4},
    {"_ifedtree_PredHonestRcpp", (DL_FUNC) &_ifedtree_PredHonestRcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ifedtree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
