# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get honest predictions (C++)
#'
#' Computes honest predictions (fitted values) from the random forest
#' for the train and honest sample based on the honest training sample.
#'
#' @useDynLib ifedtree
#' @param x unique_leaves (List)[ntree]
#' @param y honest_y (NumericVector)[nrow]
#' @param z honest_leaves (NumericMatrix)[nrow, ntree]
#' @param w train_leaves (NumericMatrix)[nrow, ntree]
#' @keywords internal
#' @source \url{https://github.com/okasag/orf/blob/master/orf/src/get_honest_rcpp.cpp}
GetHonestRcpp <- function(x, y, z, w) {
    .Call('_ifedtree_GetHonestRcpp', PACKAGE = 'ifedtree', x, y, z, w)
}

#' Predict honest predictions (C++)
#'
#' Computes honest predictions from the random forest for
#' a test sample based on the honest training sample.
#'
#' @useDynLib ifedtree
#' @param x unique_leaves (List)[ntree]
#' @param y honest_y (NumericVector)[nrow]
#' @param z honest_leaves (NumericMatrix)[nrow, ntree]
#' @param w test_leaves (NumericMatrix)[nrow, ntree]
#' @keywords internal
#' @source \url{https://github.com/okasag/orf/blob/master/orf/src/pred_honest_rcpp.cpp}
PredHonestRcpp <- function(x, y, z, w) {
    .Call('_ifedtree_PredHonestRcpp', PACKAGE = 'ifedtree', x, y, z, w)
}

